package zeus;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import zeus.command.Command;
import zeus.command.CommandContext;
import zeus.exception.ZeusException;
import zeus.parser.Parser;
import zeus.storage.Storage;
import zeus.task.TaskList;
import zeus.ui.ConsoleUi;
import zeus.ui.Ui;

/** Coordinates the components of the Zeus chatbot application. */
public class Zeus {
    /** Greeting shown when the graphical interface starts. */
    private static final String WELCOME_MESSAGE = "Hello! I'm Zeus.\nWhat can I do for you?";

    /** Component responsible for console interaction. */
    private final ConsoleUi ui;

    /** Component responsible for persistent task storage. */
    private final Storage storage;

    /** Recoverable problems found while loading saved tasks. */
    private final List<String> loadWarnings;

    /** In-memory task collection used during this session. */
    private TaskList tasks;

    /** Whether the last graphical-interface command requested an exit. */
    private boolean isExitRequested;

    /**
     * Creates Zeus using the specified task data file.
     *
     * @param filePath Path of the task data file.
     */
    public Zeus(String filePath) {
        ui = new ConsoleUi();
        storage = new Storage(filePath);
        loadWarnings = new ArrayList<>();
        tasks = new TaskList(storage.load(loadWarnings));
        isExitRequested = false;
    }

    /** Runs the console command loop until the user exits or input ends. */
    public void run() {
        ui.showWelcome();
        ui.showLoadingWarnings(loadWarnings);

        while (!isExitRequested && ui.hasNextCommand()) {
            String fullCommand = ui.readCommand();
            isExitRequested = executeCommand(fullCommand, ui);

            if (!isExitRequested) {
                ui.showResponseEnd();
            }
        }
    }

    /**
     * Returns the greeting and any warnings produced while loading saved tasks.
     *
     * @return Startup message for the graphical interface.
     */
    public String getWelcomeMessage() {
        StringBuilder message = new StringBuilder(WELCOME_MESSAGE);
        for (String warning : loadWarnings) {
            message.append("\nOOPS!!! ").append(warning);
        }
        return message.toString();
    }

    /**
     * Executes one graphical-interface command and returns the generated reply.
     *
     * @param input Command entered by the user.
     * @return Reply generated by Zeus.
     */
    public String getResponse(String input) {
        ByteArrayOutputStream responseBuffer = new ByteArrayOutputStream();
        try (PrintStream responseOutput = new PrintStream(
                responseBuffer, true, StandardCharsets.UTF_8)) {
            Ui responseUi = new Ui(responseOutput);
            isExitRequested = executeCommand(input.trim(), responseUi);
        }
        return responseBuffer.toString(StandardCharsets.UTF_8).stripTrailing();
    }

    /**
     * Reports whether the most recent command requested that Zeus exit.
     *
     * @return True when the most recent command was {@code bye}.
     */
    public boolean isExitRequested() {
        return isExitRequested;
    }

    /**
     * Parses and executes one command, reporting recoverable errors through the supplied UI.
     *
     * @param fullCommand Complete command to execute.
     * @param commandUi UI that receives the command's output.
     * @return True when the command requests an exit.
     */
    private boolean executeCommand(String fullCommand, Ui commandUi) {
        try {
            Command command = Parser.parse(fullCommand);
            command.execute(new CommandContext(tasks, commandUi, storage));
            return command.isExit();
        } catch (ZeusException exception) {
            commandUi.showError(exception.getMessage());
            return false;
        }
    }

    /**
     * Starts Zeus with its project-relative data file.
     *
     * @param args Command-line arguments, which are not used.
     */
    public static void main(String[] args) {
        new Zeus("data/zeus.txt").run();
    }
}
