package zeus.ui;

import java.io.InputStream;
import java.io.PrintStream;
import java.util.List;
import java.util.Scanner;

import zeus.task.Task;

/** Handles all console input and output for the Zeus chatbot. */
public class Ui {
    /** Visual boundary used between commands and responses. */
    private static final String SEPARATOR =
            "____________________________________________________________";

    /** Name banner displayed when Zeus starts. */
    private static final String BANNER = " _____\n"
            + "|__  /___ _   _ ___\n"
            + "  / // _ \\ | | / __|\n"
            + " / /|  __/ |_| \\__ \\\n"
            + "/____\\___|\\__,_|___/\n";

    /** Source of commands entered by the user. */
    private final Scanner scanner;

    /** Destination for messages generated by Zeus. */
    private final PrintStream output;

    /** Whether console divider lines should be included in output. */
    private final boolean isSeparatorEnabled;

    /** Creates a console UI that reads from standard input. */
    public Ui() {
        this(new Scanner(System.in), System.out, true);
    }

    /**
     * Creates a response-only UI that writes messages to the supplied stream.
     *
     * @param output Destination for generated messages.
     */
    public Ui(PrintStream output) {
        this(new Scanner(InputStream.nullInputStream()), output, false);
    }

    /**
     * Creates a UI using the supplied input, output, and separator preference.
     *
     * @param scanner Source of commands.
     * @param output Destination for generated messages.
     * @param isSeparatorEnabled Whether console divider lines should be displayed.
     */
    private Ui(Scanner scanner, PrintStream output, boolean isSeparatorEnabled) {
        this.scanner = scanner;
        this.output = output;
        this.isSeparatorEnabled = isSeparatorEnabled;
    }

    /** Displays Zeus's banner and greeting. */
    public void showWelcome() {
        output.println(SEPARATOR);
        output.print(BANNER);
        output.println("Hello! I'm Zeus.");
        output.println("What can I do for you?");
        output.println(SEPARATOR);
    }

    /**
     * Reports whether another command is available.
     * @return true when another input line can be read
     */
    public boolean hasNextCommand() {
        return scanner.hasNextLine();
    }

    /**
     * Reads the next command and displays the response boundary.
     * @return trimmed command entered by the user
     */
    public String readCommand() {
        String command = scanner.nextLine().trim();
        output.println(SEPARATOR);
        return command;
    }

    /**
     * Displays recoverable problems found while loading saved tasks.
     * @param warnings loading warning messages
     */
    public void showLoadingWarnings(List<String> warnings) {
        for (String warning : warnings) {
            showError(warning);
        }
        if (!warnings.isEmpty()) {
            output.println(SEPARATOR);
        }
    }

    /**
     * Displays all tasks in their current order.
     * @param tasks tasks to display
     */
    public void showTaskList(List<Task> tasks) {
        output.println("Here are the tasks in your list:");
        for (int i = 0; i < tasks.size(); i++) {
            output.println((i + 1) + "." + tasks.get(i));
        }
    }

    /**
     * Displays matching tasks in their current order.
     *
     * @param matchingTasks Tasks whose descriptions contain the search keyword.
     */
    public void showMatchingTasks(List<Task> matchingTasks) {
        output.println("Here are the matching tasks in your list:");
        for (int i = 0; i < matchingTasks.size(); i++) {
            output.println((i + 1) + "." + matchingTasks.get(i));
        }
    }

    /**
     * Confirms that a task was marked as done.
     * @param task task whose status changed
     */
    public void showTaskMarked(Task task) {
        output.println("Nice! I've marked this task as done:");
        output.println("  " + task);
    }

    /**
     * Confirms that a task was marked as not done.
     * @param task task whose status changed
     */
    public void showTaskUnmarked(Task task) {
        output.println("OK, I've marked this task as not done yet:");
        output.println("  " + task);
    }

    /**
     * Confirms that a task was removed.
     * @param task task that was removed
     * @param taskCount number of remaining tasks
     */
    public void showTaskDeleted(Task task, int taskCount) {
        output.println("Noted. I've removed this task:");
        output.println("  " + task);
        output.println("Now you have " + taskCount + " tasks in the list.");
    }

    /**
     * Confirms that a task was added.
     * @param task task that was added
     * @param taskCount number of stored tasks
     */
    public void showTaskAdded(Task task, int taskCount) {
        output.println("Got it. I've added this task:");
        output.println("  " + task);
        output.println("Now you have " + taskCount + " tasks in the list.");
    }

    /**
     * Displays a user-friendly error message.
     * @param message explanation of the error
     */
    public void showError(String message) {
        output.println("OOPS!!! " + message);
    }

    /** Displays Zeus's farewell and, for the console, closes the final response boundary. */
    public void showGoodbye() {
        output.println("Bye. Hope to see you again soon!");
        if (isSeparatorEnabled) {
            output.println(SEPARATOR);
        }
    }

    /** Closes the response boundary for a completed command. */
    public void showResponseEnd() {
        if (isSeparatorEnabled) {
            output.println(SEPARATOR);
        }
    }
}
