package zeus.ui;

import java.io.PrintStream;
import java.util.List;

import zeus.task.Task;

/** Displays responses generated by the Zeus chatbot. */
public class Ui {
    /** Destination for messages generated by Zeus. */
    private final PrintStream output;

    /** Creates a UI that writes messages to standard output. */
    public Ui() {
        this(System.out);
    }

    /**
     * Creates a response-only UI that writes messages to the supplied stream.
     *
     * @param output Destination for generated messages.
     */
    public Ui(PrintStream output) {
        this.output = output;
    }

    /**
     * Displays all tasks in their current order.
     * @param tasks tasks to display
     */
    public void showTaskList(List<Task> tasks) {
        output.println("Here are the tasks in your list:");
        for (int i = 0; i < tasks.size(); i++) {
            output.println((i + 1) + "." + tasks.get(i));
        }
    }

    /**
     * Displays matching tasks in their current order.
     *
     * @param matchingTasks Tasks whose descriptions contain the search keyword.
     */
    public void showMatchingTasks(List<Task> matchingTasks) {
        output.println("Here are the matching tasks in your list:");
        for (int i = 0; i < matchingTasks.size(); i++) {
            output.println((i + 1) + "." + matchingTasks.get(i));
        }
    }

    /** Displays guidance for every supported command. */
    public void showHelp() {
        showLines(
                "Here are the commands you can use:",
                "  todo DESCRIPTION - Add a task without a date.",
                "  deadline DESCRIPTION /by yyyy-MM-dd - Add a task with a due date.",
                "  event DESCRIPTION /from yyyy-MM-dd /to yyyy-MM-dd - Add a task with start and end dates.",
                "  list - Show all tasks.",
                "  find KEYWORD - Find tasks whose descriptions contain the keyword.",
                "  mark NUMBER - Mark the numbered task as done.",
                "  unmark NUMBER - Mark the numbered task as not done.",
                "  delete NUMBER - Delete the numbered task.",
                "  help - Show this help page.",
                "  bye - Exit Zeus.",
                "",
                "Dates must use yyyy-MM-dd, for example 2026-09-06.");
    }

    /**
     * Confirms that a task was marked as done.
     * @param task task whose status changed
     */
    public void showTaskMarked(Task task) {
        showLines("A worthy task completed.", "  " + task);
    }

    /**
     * Confirms that a task was marked as not done.
     * @param task task whose status changed
     */
    public void showTaskUnmarked(Task task) {
        showLines("OK, I've marked this task as not done yet:", "  " + task);
    }

    /**
     * Confirms that a task was removed.
     * @param task task that was removed
     * @param taskCount number of remaining tasks
     */
    public void showTaskDeleted(Task task, int taskCount) {
        showLines(
                "Noted. I've removed this task:",
                "  " + task,
                "Now you have " + taskCount + " tasks in the list.");
    }

    /**
     * Confirms that a task was added.
     * @param task task that was added
     * @param taskCount number of stored tasks
     */
    public void showTaskAdded(Task task, int taskCount) {
        showLines(
                "It is decreed. Your task has been added.",
                "  " + task,
                "Now you have " + taskCount + " tasks in the list.");
    }

    /**
     * Displays a user-friendly error message.
     * @param message explanation of the error
     */
    public void showError(String message) {
        showLines("OOPS!!! " + message);
    }

    /** Displays Zeus's farewell. */
    public void showGoodbye() {
        showLines("Farewell, mortal.");
    }

    /**
     * Displays any number of message lines in their supplied order.
     *
     * @param lines Message lines to display.
     */
    protected void showLines(String... lines) {
        for (String line : lines) {
            output.println(line);
        }
    }
}
